// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Auto-generated sidebar from file structure (Docs folder)
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', 
    },
  ],

  // Your custom manually-controlled sidebar
  mySidebar: [
    'index',            // docs/index.mdx
    'resume-dashboard', // docs/resume-dashboard.mdx
    'pocs',             // docs/pocs.mdx
    'demos',            // docs/demos.mdx
  ],
};

export default sidebars;
